os: osx

osx_image:
  - xcode9.4
  - xcode11.3

before_script:
    - export GIT_AUTHOR_NAME=__GIT_AUTHOR_NAME__
    - export GIT_AUTHOR_EMAIL=__GIT_AUTHOR_EMAIL__
    - export PERSONAL_SPACE_GIT_AUTHOR_NAME=__PERSONAL_SPACE_GIT_AUTHOR_NAME__
    - export PERSONAL_SPACE_GIT_AUTHOR_EMAIL=__PERSONAL_SPACE_GIT_AUTHOR_EMAIL__
    - export WORK_SPACE_GIT_AUTHOR_NAME=__WORK_SPACE_GIT_AUTHOR_NAME__
    - export WORK_SPACE_GIT_AUTHOR_EMAIL=__WORK_SPACE_GIT_AUTHOR_EMAIL__
    - export PUSHOVER_TOKEN=__PUSHOVER_TOKEN__
    - export PUSHOVER_USER=__PUSHOVER_USER__

script:
  - make build
  - echo "Y" | make sync
  - cat ~/.gitconfig-personal-space
  - cat ~/.gitconfig-work-space
  - cat ~/.extra
