# MIT License
#
# Copyright (c) 2010 Clivern
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


vars:
  version: 1.16.0
  datacenter: AMS-01
  data_dir: "/opt/hashicorp/consul/data"
  node_name: "node01"
  # Private IP
  bind_addr: 127.0.0.1
  # Private IP
  client_addr: 127.0.0.1
  # Consul Server HTTP Address
  server_addr: 127.0.0.1
  # Token to communicate with consul server
  consul_server_token: f812c2b4-2530-40a1-9764-96eef8b63029

templates:
  client.hcl.j2: client.hcl.j2
  consul.service.j2: consul.service.j2

handlers:
  - name: reload consul service
    systemd:
      state: restarted
      daemon_reload: yes
      name: consul

  - name: restart consul service
    systemd:
      state: restarted
      name: consul

tasks:
  - name: install required packages
    apt:
      pkg:
      - zip
      - unzip
    become: yes

  - name: create consul directory
    file:
      path: /opt/hashicorp/consul
      state: directory
      mode: 0755
    become: yes

  - name: create consul config directory
    file:
      path: /opt/hashicorp/consul/config
      state: directory
      mode: 0755
    become: yes

  - name: create consul data directory
    file:
      path: /opt/hashicorp/consul/data
      state: directory
      mode: 0755
    become: yes

  - name: download consul
    unarchive:
      src: "https://releases.hashicorp.com/consul/{{ version }}/consul_{{ version }}_linux_386.zip"
      dest: /opt/hashicorp/consul/
      remote_src: yes
    become: yes

  - name: change perm
    file:
      dest: /opt/hashicorp/consul/consul
      mode: a+x
    become: yes

  - name: set client.hcl config file
    template:
      src: "client.hcl.j2"
      dest: "/opt/hashicorp/consul/config/client.hcl"
      mode: 0700
    notify: restart consul service
    become: yes

  - name: create consul service file
    template:
      src: consul.service.j2
      dest: /etc/systemd/system/consul.service
      mode: "0750"
    notify: reload consul service
    become: yes

  - name: enable and start consul service
    systemd:
      name: consul
      state: started
      enabled: yes
    become: yes
