name: ci

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run CI
        run: |
          pip --version
          pip install opswork
