name: CI

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run CI
        run: |
          sw_vers

          brew install yq

          python3 -m pip --version
          python3 -m pip install opswork
          python3 -m pip install ansible
          ansible --version
          opswork config init

          git submodule update --init --recursive

          make hosts
          make recipes
          make run

		  brew doctor

