name: CI

on:
  push:
    branches:
      - v2

jobs:
  CI:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run CI
        run: |
          python3 -m pip --version
          python3 -m pip install opswork
          python3 -m pip install ansible
          python3 -m pip ansible --version
          opswork config init

          make hosts
          make recipes
          make run
