name: CI

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run CI
        run: |
          cd docker

          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer -y

          docker version
          packer version

          echo "username = \"${{ secrets.USERNAME }}\"\npassword = \"${{ secrets.PASSWORD }}\"" > hub.pkrvars.hcl
          cat hub.pkrvars.hcl

          make ci
          make golang
          make rust
